version: '3.8'

services:
  dev:
    volumes:
      - ./:/app/
    build:
      dockerfile: Dockerfile
      context: .
    image: ${REGISTRY_URL}/sc2-serializer:latest
    tty: true
    restart: unless-stopped
