apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sc2
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: extract
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: dkr-creds
            - name: taco
          securityContext:
            runAsUser: 1000
          containers:
            - name: runner
              image: mu00120825.eng.monash.edu.au:5021/sc2-serializer:latest
              # command:
              # [
              #   "./sc2_merger",
              #   "--folder=/mnt/storage/converted/4.9.2",
              #   "--merge",
              #   "--output=mnt/storage/converted/492_merged",
              # ]
              command: ["/bin/bash", "-c", "--"]
              args: ["while true; do sleep 30; done;"]
              env:
                - name: SC2PATH
                  value: /mnt/storage/SC2/4.9.2/
                - name: CUDA_VISIBLE_DEVICES
                  value: "-1"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              resources:
                requests:
                  memory: 2.5Gi
                limits:
                  memory: 6Gi
                  cpu: 1500m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
          volumes:
            - name: storage
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys
