---
name: Docs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Requirements
        run: |
          sudo apt-get update
          sudo apt-get install doxygen sphinx-doc python3-sphinx-rtd-theme python3-breathe pipx
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Need to build main library for python bindings.
        run: pipx install .
      - name: Build docs
        run: |
          mkdir -p docs/_build/html/_sources
          cp -r src/sc2_replay_reader docs/_build/html/_sources/sc2_replay_reader
          make -C docs html
          touch docs/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
