name: Documentation Workflow

# on:
#   push:
#     branches:
#       - main  # Change this to your main branch name
on: [push]

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest

    outputs:
      doxygen-xml-path: ${{ steps.build_doxygen.outputs.doxygen-xml-path }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: |
          mkdir -p docs/doxygen
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        id: build_doxygen
        run: |
          doxygen Doxyfile
          echo "::set-output name=doxygen-xml-path::path/to/doxygen/xml"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx breathe

      - name: Generate Sphinx Configuration
        run: |
          sphinx-quickstart --quiet --sep --project="sc2-serializer" --author="Bryce Ferenczi & Rhys Newbury" --ext-autodoc

      - name: Build Sphinx Documentation
        run: |
          make html
