---
name: Docs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Requirements
        run: |
          sudo apt-get update
          sudo apt-get install doxygen sphinx-doc cmake pipx libboost-iostreams1.74-dev libtbb-dev
          pipx install sphinx-rtd-theme breathe black git+https://github.com/5had3z/pybind11-stubgen.git
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build main library for python bindings
        run: pipx install .
      - name: Build docs
        run: |
          make -C docs html
          touch docs/_build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
