name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake-version: [3.22]
        gcc-version: [13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote

      - name: Set up CMake, GCC, and G++
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-${{ matrix.gcc-version }} gcc-${{ matrix.gcc-version }}
          sudo apt-get install -y cmake ninja-build git libboost-iostreams1.74-dev
      - name: Fix python setup issues
        run : |
          sudo apt-get purge -y python3-setuptools
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          pip install --upgrade pip

      - name: Configure CMake
        run: |
          export CC="/usr/bin/gcc-${{ matrix.gcc-version }}"
          export CXX="/usr/bin/g++-${{ matrix.gcc-version }}"
          cmake -B build -G Ninja -DSC2_PY_READER=OFF -DSC2_TESTS=ON

      - name: Build and run tests
        run: cmake --build build --parallel --config Release && ./build/test_database && ./build/test_readwrite

      - name: Ensure pybind11-stubgen installed
        run: pip install git+https://github.com/5had3z/pybind11-stubgen.git black

      - name: Run python building
        run: pip install .

      - name: Check the python imports
        run: python -c "import sc2_replay_reader; db = sc2_replay_reader.ReplayDatabase()"
